### ISSUE TITLE
Add example image

### ISSUE THREAD

**Issue by KristjanESPERANTO** [martinburheimtingstad/MMM-AquareaSmartCloud#1]
Can you add an example image directly to the repository? For example as `screenshot.png` or `example.png` in any folder :slightly_smiling_face: 

This would have the advantage that the image would be displayed in [the module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on.

**Comment by martinburheimtingstad** [comment]
Thanks for the heads up, will get this done tonight!Best regards,MartinSent from my iPhoneOn 18 Dec 2023, at 14:51, Kristjan ESPERANTO ***@***.***> wrote:﻿
Can you add an example image directly to the repository? For example as screenshot.png or example.png in any folder 🙂
This would have the advantage that the image would be displayed in the module list I am working on.

**Comment by KristjanESPERANTO** [comment]
Very nice. Your module is now displayed on the above-mentioned list with screenshot :slightly_smiling_face:
